print("")
print("Multiplica ")
print("")
print("Ingresa un numero a multiplicar ")
num1 = int(input())
print("Ingresaste el numero", num1)
print("")
print("Ingresa el segundo numero a multiplicar ")
num2 = int(input())
print("Ingresaste ", num2)
print("Presiona enter para multiplicar ")
enter = input()
print("La multiplicacion entre ", num1, " y ", num2, " es ", num1 * num2)
print("")
print("FIN MULTIPLICAR ")